# Generated by Django 3.0.8 on 2020-07-26 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200718_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ts',
            field=models.DateField(default=datetime.datetime(2020, 7, 26, 17, 8, 15, 857553)),
        ),
    ]
