# Generated by Django 3.0.8 on 2020-09-07 20:09

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200726_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 16, 9, 55, 442801)),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
