# Generated by Django 3.0.8 on 2020-10-11 22:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200907_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 18, 3, 44, 697670)),
        ),
    ]
